/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewFileIdRouteImport } from './routes/view.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewFileIdRoute = ViewFileIdRouteImport.update({
  id: '/view/$fileId',
  path: '/view/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/view/$fileId': typeof ViewFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/view/$fileId': typeof ViewFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/view/$fileId': typeof ViewFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/view/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/view/$fileId'
  id: '__root__' | '/' | '/view/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewFileIdRoute: typeof ViewFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$fileId': {
      id: '/view/$fileId'
      path: '/view/$fileId'
      fullPath: '/view/$fileId'
      preLoaderRoute: typeof ViewFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewFileIdRoute: ViewFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
